- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - copy_moodle_siteNdata
    - create_db_backup
    - update_config_file
    - createNcopystoragezip

- hosts: webservers
  roles:
    - restore_db_backup
    - restore_site_backup
    - replication