- hosts: 127.0.0.1
  connection: local
  roles:
    #- enable_maintenance_mode
    - sshkeyconfig # done
    - create_db_backup # done
    - copy_moodle_siteNdata #copy_moodledata_site_dir  # done
    - update_config_file
    - createNcopystoragezip #- copy_storage_to_target_location  # done

- hosts: webservers
  roles:
    - restore_db_backup  # done
    - restore_site_backup # done
    - replication  # done
   # - disable_maintenance_mode

    # if DB restore fails in between then control should transfer
    # to the new role which will delete created DB.

    # if restore_site_backup fails then remove the copied content