---
- name: Create a zip archive of storage
  archive:
    path: "{{storage_dir_path}}"
    format: zip
    dest: /home/azureadmin/storage.zip
  become: yes

-
  name: "copy storage.zip file to remote host"
  command: scp /home/{{user_name}}/storage.zip {{user_name}}@{{tar_vm_ip}}:/home/{{user_name}}
  become: yes
