---
- name: Create a zip archive of storage
  archive:
    path: "{{storage_dir_path}}"
    format: tar
    dest: /home/azureadmin/storage.tar
  become: yes

-
  name: "copy storage.zip file to remote host"
  command: scp /home/{{user_name}}/storage.tar {{user_name}}@{{tar_vm_ip}}:/home/{{user_name}}
  become: yes

-
  name: "copy DB dump file to remote host"
  command: scp /home/{{user_name}}/database.sql {{user_name}}@{{tar_vm_ip}}:/home/{{user_name}}
  become: yes
