---

- name: Create a zip archive of /path/to/foo
  archive:
    path: {{storage_dir_path}}
    format: zip
    dest: /home/azureadmin/storage.zip

- name: Copy storage folder to target
  command: "scp  {{ db_dir_path | quote }}/storage.zip {{ user_name | quote }}@{{ tar_vm_ip | quote }}:/home/{{user_name}}"
  no_log: false
