---
-
  name: Create a stotage directory
  file:
    state: directory
    path: "{{storage_dir_path}}/"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    mode: 0755
  become: yes

- name: "change permissions of moodledata directory"
  command: "chmod 777 {{moodledata_dir}}"
  become: yes

-
  name: "copy moodledata to storage directory"
  command: "cp -rf {{moodledata_dir}} {{storage_dir_path}}"
  become: yes

-
  name: "revert permissions of moodledata directory"
  command: "chmod 770 {{moodledata_dir}}"
  become: yes

-
  name: "copy site content to storage"
  command: "cp -rf /azlamp/html/{{source_dns_name}}/ {{storage_dir_path}}"
  become: yes

-
  name: "rename site content folder name from source to target"
  command: "mv {{storage_dir_path}}/{{source_dns_name}}/ {{storage_dir_path}}/{{target_dns_name}}"
  become: yes
