---
- name: Extract storage.tar
  unarchive:
    src: "{{db_dir_path}}/storage.tar"
    dest: "{{db_dir_path}}"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    copy: no
  become: yes

-
  name: "move site contents"
  command: "mv {{storage_dir_path}}/{{target_dns_name}} /azlamp/html/"
  become: yes

-
  name: "move moodledata contents"
  command: "mv {{storage_dir_path}}/moodledata/ /azlamp/"
  become: yes

-
  name: "set permissions to moodledata"
  command: "chmod 770 {{moodledata_dir}}"
  become: yes
