---
-
  name: "restore site directory"
  command: "cp -rf {{storage_dir_path}}/{{old_domain_name}}/* /azlamp/html/{{new_domain_name}}/"
  # sudo cp -rf /home/azureadmin/storage/lb-6qudgw.eastus.cloudapp.azure.com/* /azlamp/html/lb-43enuc.eastus.cloudapp.azure.com/

