---
- name: Install MySQL 
  apt: 
    name: mysql-server
    state: latest
  become: yes
-
  name: "create a backup database"
  command: "mysqldump -h {{source_db_server_name}} -u {{source_db_login_name}} -p{{source_db_pass}} {{source_db_name}} > {{db_dir_path}}/database.sql"
  become: yes
#mysqldump -h mysql-24qd5n.mysql.database.azure.com -u dbadmin@mysql-24qd5n -piTalent@27 moodle > /home/azureadmin/database.sql