---
- name: Create a new stotage directory
  file:
    state: directory
    path: "{{storage_dir_path}}"
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    mode: 0755
  become: yes

- name: "change permissions of moodledata directory"
  command: "chmod 777 {{moodledata_dir}}"
  become: yes

-
  name: "copy moodledata to new directory"
  command: "cp -rf {{moodledata_dir}} {{storage_dir_path}}"
  become: yes

- name: "revert permissions of moodledata directory"
  command: "chmod 770 {{moodledata_dir}}"
  become: yes

-
  name: "copy site new directory"
  command: "cp -rf {{site_dir_path}} {{storage_dir_path}}"
  become: yes

-
  name: "copy database backup file to storage"
  command: "cp {{db_dir_path}}/moodle-database.sql {{storage_dir_path}}"
  become: yes

