--- 
- 
  apt: 
    upgrade: true
  become: true
  name: upgrade
- 
  apt: 
    name: sshpass
    state: latest
  become: true
  name: "install sshpass"
- 
  become: true
  name: "generate sshkey"
  openssh_keypair: 
    group: azureadmin
    owner: azureadmin
    path: /home/azureadmin/.ssh/id_rsa
    size: 4096
- 
  command: "sshpass -p iTalent@27 ssh-copy-id -i /home/azureadmin/.ssh/id_rsa.pub -o StrictHostKeyChecking=no azureadmin@52.255.140.119"
  name: "copy file to remote host"


# ---
# -
#   name: "upgrade"
#   apt:
#     upgrade: true
#   become: true
# -
#   name: "install sshpass"
#   apt:
#     name: sshpass
#     state: latest
#   become: true
# -
#   name: "generate sshkey"
#   openssh_keypair:
#     path: /home/azureadmin/.ssh/id_rsa
#     group: azureadmin
#     owner: azureadmin
#     size: 4096
#   become: yes
# -
#   name: "copy file to remote host"
#   command: sshpass -p iTalent@27 ssh-copy-id -i /home/azureadmin/.ssh/id_rsa.pub -o StrictHostKeyChecking=no azureadmin@52.255.140.119

